name: Model Retraining and Docker Deployment

on:
  push:
    branches: [ main ]

jobs:
  train-and-build:
    runs-on: ubuntu-latest
    steps:
      # 1. Mengunduh kode dari repositori GitHub ke runner
      - name: Checkout Code
        uses: actions/checkout@v4
      
      # 2. Menyiapkan lingkungan Python versi 3.12.7 sesuai spesifikasi
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12.7'
          
      # 3. Menginstal seluruh dependency yang dibutuhkan untuk proses training
      - name: Install Dependencies
        run: |
          pip install mlflow==2.19.0 dagshub pandas scikit-learn
          
      # 4. Menjalankan MLflow Project Retraining & Menangkap Run ID Baru
      - name: Run MLflow Project Retraining
        id: train_model
        env:
          DAGSHUB_USERNAME: ${{ secrets.DAGSHUB_USERNAME }}
          DAGSHUB_TOKEN: ${{ secrets.DAGSHUB_TOKEN }}
        run: |
          # Jalankan training dan simpan output log-nya ke file teks
          mlflow run MLProject --env-manager local -P n_estimators=120 -P max_depth=12 > train_log.txt
          cat train_log.txt
          
          # Mengambil Run ID bersih dari log menggunakan perintah grep
          RUN_ID=$(grep -oP "TARGET_RUN_ID:\K.*" train_log.txt)
          echo "Ditemukan Run ID untuk Docker: $RUN_ID"
          
          # Menyimpan Run ID ke output agar bisa diakses oleh step berikutnya
          echo "RUN_ID=$RUN_ID" >> $GITHUB_OUTPUT

      # 5. Autentikasi ke akun Docker Hub menggunakan GitHub Secrets
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 6. Mengemas model MLflow menjadi Docker Image (Syarat Advance)
      - name: Build Docker Image from MLflow Model
        env:
          DAGSHUB_USERNAME: ${{ secrets.DAGSHUB_USERNAME }}
          DAGSHUB_TOKEN: ${{ secrets.DAGSHUB_TOKEN }}
        run: |
          # Menggunakan RUN_ID yang didapat dari step 'train_model'
          # Menggunakan flag --enable-mlserver untuk performa serving yang optimal
          mlflow models build-docker \
            -m "runs:/${{ steps.train_model.outputs.RUN_ID }}/model" \
            -n "${{ secrets.DOCKERHUB_USERNAME }}/credit-card-model:latest" \
            --enable-mlserver

      # 7. Mengunggah Docker Image yang berhasil di-build ke Docker Hub
      - name: Push Docker Image to Docker Hub
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/credit-card-model:latest