name: Model Training CI

on: [push] # Akan jalan setiap kali ada push ke folder manapun

jobs:
  train:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12.7'
          
      - name: Install dependencies
        run: |
          pip install mlflow dagshub pandas scikit-learn matplotlib
          
      - name: Run Training
        env:
          DAGSHUB_USERNAME: ${{ secrets.DAGSHUB_USERNAME }}
          DAGSHUB_TOKEN: ${{ secrets.DAGSHUB_TOKEN }}
        run: |
          # Melihat isi folder agar tahu posisi file sebenarnya
          ls -R
          
          # Gunakan jalur relatif dari akar repositori
          # Pastikan penulisan huruf besar/kecil SAMA PERSIS dengan di GitHub
          python Membangun_model/modelling_tuning.py